feat: init repo
helpwave/services pull request #1
Opened 2022-12-16 15:15 UTC by FoseFx

2022-12-17 18:26 UTC, JannikWibker commented
![image](https://user-images.githubusercontent.com/16372321/208256105-e7fe6b6d-5cc7-4587-b815-c0c15e1d3c3f.png)

any particular reason for this?, this seems like a rather long list

2022-12-17 18:27 UTC, FoseFx commented
copy & paste from hw/rest-api

2022-12-17 18:32 UTC, JannikWibker commented
ahh true
then the question becomes why hw/rest-api had to have gitignore entries for vim, emacs, dart, flutter, android, pycharm, react, react native, python, xcode, node, cordova, vue, etc.

2022-12-18 11:45 UTC, MaxSchaefer commented
The user-svc is a nice example for now, but in the futures the organization-part should be handled by a separate service.

2022-12-18 14:50 UTC, FoseFx commented
As of today's meeting we scrap Auth v1 anyway (in favor of a IAM solution, Keycloak?), so this service will probably experience heavy changes anyway.

2022-12-18 16:09 UTC, MaxSchaefer commented
> As per today's meeting we scrap Auth v1 anyway (in favor of a IAM solution, Keycloak?), so this service will probably experience heavy changes anyway.

Yes, Keycloak was the plan.

2022-12-18 16:25 UTC, MaxSchaefer requested changes

2022-12-18 16:25 UTC, MaxSchaefer commented on .gitignore
> +# Created by https://www.toptal.com/developers/gitignore/api/vim,emacs,dart,flutter,android,androidstudio,intellij,intellij+all,intellij+iml,pycharm,pycharm+all,pycharm+iml,go,goland,goland+iml,golan
Already discussed [here](https://github.com/helpwave/services/pull/1#issuecomment-1356375726).

2022-12-18 16:25 UTC, MaxSchaefer commented on services/user-svc/README.md
> +> User and Organization management service
```suggestion
> User management service
```

2022-12-20 10:49 UTC, MaxSchaefer approved these changes
Nice! This should unblock the other pull requests.

2022-12-20 10:49 UTC, MaxSchaefer commented on .gitignore
> +# Created by https://www.toptal.com/developers/gitignore/api/go,vim,goland,intellij,goland+all,goland+iml,intellij+all,intellij+iml,visualstudiocode
I guess not perfect but okay for now.

2022-12-20 20:17 UTC, merged