add missing methods
helpwave/services pull request #160
Opened 2023-05-22 17:34 UTC by DasProffi

closes #146 
Blocked by #153

2023-05-28 12:08 UTC, MaxSchaefer requested changes

2023-05-28 12:08 UTC, MaxSchaefer commented on proto/services/task_svc/v1/ward_svc.proto
> +  string organization_id = 1;
_See above comment. Request will be already scoped._

2023-06-02 22:29 UTC, MaxSchaefer commented on proto/services/task_svc/v1/ward_svc.proto
> +  string organization_id = 3;
In that case, the `organization_id` shoudl be already known by the client due to the header. I will remove the id here.

2023-06-02 22:50 UTC, MaxSchaefer approved these changes

2023-06-02 22:51 UTC, MaxSchaefer commented
@FoseFx I've also changed some code and reviewed this. Can you take a quick look?

2023-06-03 13:48 UTC, FoseFx approved these changes

2023-06-03 19:30 UTC, merged