feat(room): check and add methods for room-svc
helpwave/services pull request #166
Opened 2023-05-27 13:51 UTC by shivadharmi

closes https://github.com/helpwave/services/issues/147

2023-05-27 14:24 UTC, MaxSchaefer requested changes

2023-05-27 14:24 UTC, MaxSchaefer commented on services/task-svc/internal/room/models/models.go
> +	WardID         uuid.UUID `gorm:"column:ward_id"`
We should use the `Ward` as an entity.

2023-06-02 22:07 UTC, MaxSchaefer commented
Hey @shivadharmi, are you keeping track of the requested changes, or can I help you with that?

2023-06-03 17:54 UTC, use-to commented on services/task-svc/internal/room/room.go
> +	// TODO: Auth
Authorization

2023-06-03 17:54 UTC, use-to commented on services/task-svc/internal/room/room.go
> +	// Do we need to delete the beds when we delete room?
Yes, this is required.

2023-06-09 23:33 UTC, MaxSchaefer approved these changes

2023-06-09 23:39 UTC, merged