feat: first draft for accept invites
helpwave/services pull request #183
Opened 2023-06-09 12:52 UTC by florian-sabonchi

closes #180

2023-06-09 15:44 UTC, use-to requested changes
Rename to `AcceptInvitation`

2023-06-10 18:02 UTC, MaxSchaefer requested changes
> This method should allow an authenticated user to move an invitation from Pending to Accepted. The user should also be a part of the organization afterwards.

- [ ] Only allow the acceptance of an invitation when the current state is pending. When the invitation is already accepted, return a success to be idempotent.
- [ ] Add user to the organization
- [ ] Check if the email of the invitation equals the current user

2023-06-11 19:22 UTC, MaxSchaefer requested changes

2023-06-11 19:22 UTC, MaxSchaefer commented on services/user-svc/internal/organization/organization.go
> +	userID, err := uuid.Parse(claims.Sub)
```suggestion
	userID, err := common.GetUserID(ctx)
```

2023-06-11 19:22 UTC, MaxSchaefer commented on services/user-svc/internal/organization/organization.go
> +	if err := db.Where("email = ? AND organization_id = ?", req.Email, organizationId).First(&invite).Error; err != nil {
Thank you for thinking of it. Beside email and organization, we should also check if the invitation is in progress. That means, only create a new invitation if we not find one with `state == Pending` or `state == Accepted`.

2023-06-11 19:25 UTC, florian-sabonchi commented on services/user-svc/internal/organization/organization.go
> +	}
Sorry, not seen thanks

2023-06-12 22:27 UTC, MaxSchaefer approved these changes
Good job 🙌 (squash please)

2023-06-12 22:28 UTC, MaxSchaefer commented
@use-to pending requested changes

2023-06-12 22:45 UTC, use-to approved these changes

2023-06-13 06:49 UTC, merged