feat: first draft for GetInvitationsByUser
helpwave/services pull request #197
Opened 2023-06-16 15:24 UTC by florian-sabonchi

closes #193

2023-06-16 18:26 UTC, MaxSchaefer requested changes

2023-06-16 18:26 UTC, MaxSchaefer commented on proto/services/user_svc/v1/organization_svc.proto
> +  string state = 2;
```suggestion
  optional string state = 1;
```

This change will break some logic. Cam we validate this using gotags?

2023-06-19 16:19 UTC, FoseFx approved these changes

2023-06-19 16:19 UTC, FoseFx commented on services/user-svc/internal/organization/organization.go
> +		}
else case is missing, please make sure this is deliberate, maybe add a comment

2023-06-19 22:32 UTC, MaxSchaefer approved these changes
Noice 🫡

2023-06-19 22:32 UTC, MaxSchaefer commented on services/user-svc/internal/organization/organization.go
> +
```suggestion
```

2023-06-20 06:10 UTC, merged