add Create Task Template
helpwave/services pull request #202
Opened 2023-06-20 13:57 UTC by DasProffi

## Which issues does this pull request close?
closes #201

2023-06-20 18:26 UTC, DasProffi commented
The method fail because of the ward foreign key constraint being nullable, how do we fix this @MaxSchaefer or do we have solution already somewhere?

2023-06-21 09:44 UTC, DasProffi commented
@MaxSchaefer the proto bufs fail although nothing changed

2023-06-21 14:26 UTC, use-to commented
WTF is that commit message?!

2023-06-21 14:27 UTC, MaxSchaefer commented
@DasProffi I've checked that ward_id Issue, was not aware that you already fixed that. Take a look https://github.com/helpwave/services/pull/202/commits/fada8ea152374746ce686e89cd2c7f5e8626d788

2023-06-22 18:14 UTC, DasProffi commented
> @DasProffi I've checked that ward_id Issue, was not aware that you already fixed that. Take a look [fada8ea](https://github.com/helpwave/services/commit/fada8ea152374746ce686e89cd2c7f5e8626d788)

Thank you, that avoids the code duplication

2023-06-25 09:34 UTC, use-to requested changes

2023-06-25 09:34 UTC, use-to commented on services/task-svc/internal/task-template/task_template.go
> +
```suggestion
```

2023-06-25 09:34 UTC, use-to commented on services/task-svc/migrations/000010_init.up.sql
> +    user_id uuid NOT NULL,
```suggestion
	ward_id uuid DEFAULT NULL,
	user_id uuid NOT NULL,
```
indentation

2023-06-25 15:35 UTC, MaxSchaefer requested changes

2023-06-25 21:57 UTC, MaxSchaefer approved these changes
Nice. When this is merged into main, I will work on that in https://github.com/helpwave/services/pull/205 to adopt the new ward service.

2023-06-26 07:12 UTC, merged