add RevokeInvitation
helpwave/services pull request #311
Opened 2023-07-25 13:25 UTC by DasProffi

## Which issues does this pull request close?
closes #310

2023-07-25 15:31 UTC, FoseFx approved these changes

2023-07-25 16:39 UTC, DasProffi commented on services/user-svc/internal/organization/organization.go
> +		Str("organizationId", organizationID.String()).
I agree and have opened an issue for this #314

2023-07-25 18:45 UTC, MaxSchaefer requested changes

2023-07-25 18:45 UTC, MaxSchaefer commented on services/user-svc/internal/organization/organization.go
> +	}
I would prefer a new state called "Revoked".

2023-07-26 21:10 UTC, MaxSchaefer approved these changes

2023-07-26 21:10 UTC, MaxSchaefer commented on services/user-svc/internal/organization/organization.go
> +		return nil, status.Error(codes.Unauthenticated, "only admins can revoke invitations")
```suggestion
		return nil, status.Error(codes.PermissionDenied, "only admins can revoke invitations")
```

2023-07-26 21:46 UTC, merged