feat: add additional information to README.md
helpwave/services pull request #401
Opened 2023-09-08 16:35 UTC by florianjs

## Which issues does this pull request close?
closes #400

## [OPTIONAL] Give testing instructions to reviewers

2023-09-09 14:34 UTC, MaxSchaefer requested changes

2023-09-09 14:34 UTC, MaxSchaefer commented on README.md
> +	- `dapr-app-id: service-name`
```suggestion
7. For direct client to service requests via gRPC, add the following metadata to your requests:
	- `X-Organization: [An organization id. Most requests are performed on the side of an organization. The id must be part of your passed access token]`
	- `dapr-app-id: [the app id of the targeted service]`
```

2023-09-09 16:03 UTC, DasProffi approved these changes

2023-09-10 18:37 UTC, MaxSchaefer approved these changes

2023-09-11 06:11 UTC, merged