chore: python prototype service
helpwave/services pull request #489
Opened 2023-10-25 16:20 UTC by Paul-B98

## Which issues does this pull request close?
closes #487

2023-11-12 16:38 UTC, Paul-B98 commented
I will add a GraphQL example in the near future. At the moment Strawberry is my preferred lib: https://strawberry.rocks/docs/integrations/django#async-django

2023-12-30 00:23 UTC, MaxSchaefer requested changes
- Can we get rid of the `services/impulse_svc/gen` directory?
- It seams like that `libs/python` handles djano so please rename this libe to to something like `libs/hwdjano`
- Revisit the empty READMEs

2023-12-30 00:23 UTC, MaxSchaefer commented on libs/python/README.md
Empty. Write or remove.

2023-12-30 00:23 UTC, MaxSchaefer commented on libs/python/django_grpc/README.md
Empty. Write or remove.

2024-01-01 17:51 UTC, Paul-B98 commented
> * Can we get rid of the `services/impulse_svc/gen` directory?

Should be possible... I just have to find a goof way to package the gen code correctly.

> * It seams like that `libs/python` handles djano so please rename this libe to to something like `libs/hwdjano`

This was the result of our conversation where we made the decision that we create a language folder structure under lib like the `gen` folder.

2024-01-24 22:21 UTC, MaxSchaefer requested changes
- [x] Green CI
- [x] Functional Docker Build of `impulse_svc`

2024-02-10 22:00 UTC, MaxSchaefer commented
@Paul-B98 green ci?

2024-02-19 20:49 UTC, MaxSchaefer approved these changes

2024-02-19 20:58 UTC, merged