sqlc: beds, tasks and patients (WIP)
helpwave/services pull request #566
Opened 2023-12-01 10:02 UTC by FoseFx

## Which issues does this pull request close?
closes #

## [OPTIONAL] Give testing instructions to reviewers

2023-12-04 13:50 UTC, FoseFx commented
Done with Phase I: All tests are passing.

2023-12-06 20:55 UTC, MaxSchaefer commented on services/task-svc/repos/room_repo.sql
> +-- name: GetRoomWithBedsById :many
```suggestion
-- name: GetRoomWithBedsById :one
```
@FoseFx

2023-12-06 21:49 UTC, FoseFx commented on services/task-svc/repos/room_repo.sql
> +-- name: GetRoomWithBedsById :many
nope! JOIN can lead to multiple rows

2023-12-07 20:01 UTC, MaxSchaefer requested changes
Looks good so far.
Found one error in Endpoint `GetRecentPatients`:

```
failed to encode args[0]: unable to encode []uuid.UUID{uuid.UUID{0x6a, 0x7a, 0x8d, 0xfe, 0x5f, 0x8f, 0x4b, 0x7f, 0xa9, 0xf6, 0xd, 0xf0, 0xd2, 0xbf, 0x14, 0x23}, uuid.UUID{0xc1, 0xf7, 0x6e, 0xd5, 0xcd, 0x56, 0x48, 0xbe, 0x96, 0x5, 0x7f, 0x6b, 0x6, 0x4d, 0xcb, 0x33}, uuid.UUID{0x9b, 0xa7, 0x7, 0x3d, 0x94, 0xc6, 0x43, 0x35, 0x99, 0xd7, 0x1b, 0x10, 0xc6, 0xf8, 0x91, 0x51}, uuid.UUID{0x97, 0xf0, 0xd2, 0x87, 0x34, 0x98, 0x41, 0x4c, 0xba, 0xb9, 0xf, 0x34, 0x1b, 0x32, 0x8a, 0xe4}} into binary format for uuid (OID 2950): cannot find encode plan

```

2023-12-09 23:58 UTC, MaxSchaefer approved these changes

2023-12-10 11:44 UTC, merged