sqlc: tasks
helpwave/services pull request #581
Opened 2023-12-08 14:28 UTC by FoseFx

## Which issues does this pull request close?
Closes #580,
Closes #575,
Closes #570,
Closes #563,
Closes #562

AssignedUserId is now optional (breaking!)

tests 27 and 28 are flaky, might need to run it a few times (#572)

2023-12-23 13:39 UTC, MaxSchaefer commented
@FoseFx r4r?

2023-12-23 13:40 UTC, FoseFx commented
No, missing tests

2024-01-11 23:15 UTC, MaxSchaefer commented
I guess blocked by https://github.com/helpwave/services/pull/593

2024-01-13 13:30 UTC, MaxSchaefer commented
@FoseFx unblocked?

2024-01-20 16:02 UTC, MaxSchaefer requested changes

2024-01-20 16:02 UTC, MaxSchaefer commented on services/task-svc/internal/task/task.go
> +	if err := taskRepo.UpdateTask(ctx, task_repo.UpdateTaskParams{ID: id, Public: &public}); err != nil {
`hwutil.PtrTo(true)`

2024-01-20 16:02 UTC, MaxSchaefer commented on services/task-svc/internal/task/task.go
> +	}); err != nil {
```suggestion
	if err := taskRepo.UpdateTask(ctx, task_repo.UpdateTaskParams{
		Public: hwutil.PtrTo(false),
		ID:     id,
	}); err != nil {
```

2024-01-21 10:59 UTC, FoseFx commented on services/task-svc/internal/task/task.go
> +	taskMap := make(map[uuid.UUID]int)
id -> index map

if task was seen before (i.e. already has a GetTasksByPatientResponse_Task object), mutate that one else, create it

2024-01-21 11:02 UTC, FoseFx commented on libs/hwdb/helper.go
> +func TimeToTimestamp(src time.Time) pgtype.Timestamp {
it's a constructor, not much to test

2024-01-21 11:09 UTC, FoseFx commented on libs/hwdb/helper.go
> +func PbToTimestamp(src *timestamppb.Timestamp) pgtype.Timestamp {
Because there is _some_ logic (a nil guard) I added a test, but testing this kind of function is just a burden with no benefit

2024-01-22 16:31 UTC, MaxSchaefer approved these changes

2024-01-23 08:55 UTC, merged