adds missing endpoints in tasks-svc
helpwave/services pull request #768
Opened 2024-05-27 21:57 UTC by PaulKalho

## Which issues does this pull request close?
closes #703

2024-09-03 16:17 UTC, MaxSchaefer requested changes
Response of `GetPatientDetails`. Take a look at the `assigned_user_id`. Same for `GetPatientList` and `GetTasksByPatient`.
```
{
    "tasks": [
        {
            "subtasks": [],
            "id": "14724cf7-175b-4804-ba90-e922d4603745",
            "name": "asd",
            "description": "test",
            "status": "TASK_STATUS_IN_PROGRESS",
            "patient_id": "",
            "public": false,
            "assigned_user_id": "00000000-0000-0000-0000-000000000000"
        }
    ],
    "id": "643afb22-c8f6-4dd8-909b-303fa58cc3ad",
    "human_readable_identifier": "asd",
    "notes": "asd",
    "is_discharged": false
}
```

Cannot test `GetPatientByBed`, `GetPatientByBed`, `GetPatientAssignmentByWard` because I cannot create beds and wards.

2024-09-04 13:23 UTC, PaulKalho commented on services/tasks-svc/schema.sql
> +    created_at timestamp without time zone DEFAULT '1970-01-01 00:00:00'::timestamp without time zone NOT NULL
Why? Which handler do you mean? Should `due_at` allow NULL values? I would have to alter the logic inside the projections to insert a default date on creation, why can we not leave it to the db?

2024-09-04 16:27 UTC, MaxSchaefer commented on services/tasks-svc/schema.sql
> +    created_at timestamp without time zone DEFAULT '1970-01-01 00:00:00'::timestamp without time zone NOT NULL
`due_at` null
`created_at` remove default

2024-09-05 13:10 UTC, MaxSchaefer approved these changes

2024-09-05 13:11 UTC, merged