chore: add FEATURE_FLAG_HWAUTHZ_SPICEDB_CHECKS_ALWAYS_TRUE
helpwave/services pull request #803
Opened 2024-09-05 15:56 UTC by MaxSchaefer

This pull requests adds the feature flag `FEATURE_FLAG_HWAUTHZ_SPICEDB_CHECKS_ALWAYS_TRUE` for `hwauthz`. Currently we do not have a prod/staging ready SpiceDB config.

2024-09-05 19:57 UTC, PaulKalho approved these changes

2024-09-05 20:02 UTC, FoseFx commented
No? Just don't add checks if we don't have a proper permission to check against. (We can comment out the existing dummy ones if they cause problems). Also such a flag is NOT a feature flag! Instead it must be prefixed with INSECURE_ or alike

2024-09-05 20:02 UTC, FoseFx requested changes
^^

2024-09-16 19:25 UTC, MaxSchaefer commented
@FoseFx feel free to take this PR over. We need a solution to allow for a short period of time, until proper spicedb schemas are in place, all permission checks. So that our clients can develop further. The intro of SpiceDB was heavily breaking.

2024-09-17 10:29 UTC, closed without merging

2024-09-17 10:29 UTC, MaxSchaefer commented
https://github.com/helpwave/services/pull/817 already removes checks. For proper authZ checks, we need to wait for https://github.com/helpwave/services/pull/832