feat: unassign bed on discharge
helpwave/services pull request #848
Opened 2024-10-04 10:12 UTC by PaulKalho

## Which issues does this pull request close?
closes #843

2024-10-05 11:57 UTC, MaxSchaefer requested changes
Shouldnt we rather solve this in the projections? The bed UUID is not a part of the unassigned event, therefore we should not pass this to `UnassignBed`.
Also please add a test in our stories for this behaviour.

2024-10-05 12:57 UTC, PaulKalho commented
> Shouldnt we rather solve this in the projections? The bed UUID is not a part of the unassigned event, therefore we should not pass this to `UnassignBed`. Also please add a test in our stories for this behaviour.

As you referred to the logic checking of the `bedID`: In my opinion, logically wrong events should not be published. We, most probably, have these kind of situations elsewhere in the code. I created an issue for that: https://github.com/helpwave/services/issues/854

2024-10-07 07:14 UTC, FoseFx commented
> Shouldnt we rather solve this in the projections?

I think this is fine. It's like the handler reacts to its own event and publishes another one on top.

2024-10-17 08:59 UTC, FoseFx approved these changes

2024-10-19 22:16 UTC, MaxSchaefer approved these changes

2024-10-21 10:17 UTC, merged