added getTaskTemplate
helpwave/services pull request #849
Opened 2024-10-04 15:37 UTC by PaulKalho

## Which issues does this pull request close?
closes #846

2024-10-05 11:23 UTC, MaxSchaefer requested changes
Can you update `getTaskTemplate()` in `TaskTemplateCRUD_test.go` to use `GetTaskTemplate`. Later on in `TestCreateUpdateGetTaskTemplate()` you can try `GetAllTaskTemplates` so both methods are tested.

2024-10-06 16:46 UTC, FoseFx approved these changes

2024-10-06 16:46 UTC, FoseFx commented on services/tasks-svc/internal/task-template/task_template.go
> +		st := &pb.GetTaskTemplateResponse_SubTask{
nit: could be an immediate return

2024-10-09 08:30 UTC, FoseFx commented on services/tasks-svc/repos/task_template_repo.sql
> +-- name: GetTaskTemplateWithSubtaskByID :many
```suggestion
-- name: GetTaskTemplateWithSubtasksByID :many
```

2024-10-09 08:30 UTC, FoseFx commented on services/tasks-svc/stories/TaskTemplateCRUD_test.go
> +	templates, err := taskTemplateClient.GetAllTaskTemplates(ctx, &pb.GetAllTaskTemplatesRequest{})
is there anything scoping the task templates response here (e.g., user, orga, ...)? if not this is racy against other tests, which might create task templates

2024-10-14 16:17 UTC, MaxSchaefer approved these changes

2024-10-14 16:18 UTC, merged